name: QulertsNotificationExtension

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Swift environment
      uses: actions/setup-swift@v1
      with:
        swift-version: '5.10.0'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
