name: QulertsNotificationExtension

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.10.0"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create Tag
      run: |
        git tag -a 1.0.${{ github.run_number }} -m "Release version 1.0.${{ github.run_number }}"
        git push origin 1.0.${{ github.run_number }}
